### ISSUE TITLE
Proper workout stats

### ISSUE THREAD

**Issue by n6g7** [enkidevs/commit#1]
Hi Enki,

Why not use the [github/linguist override](https://github.com/github/linguist#overrides) options to fix GitHub's broken language bar?
<img width="988" alt="capture d ecran 2016-06-21 a 14 18 13" src="https://cloud.githubusercontent.com/assets/3386177/16230815/3d30be12-37bb-11e6-8c0f-b070cdea7e0e.png">

ATM "Git" and "Linux" workouts are both part of the "Shell" section because they have the same file extention (`.bash`).

Should be easy to fix if you can decide on a mapping between workout topics and file extensions.

**Comment by mathieudutour** [comment]
Hi Nathan,

hum I used linguist a bit and you only have the power to override the mapping between some file extensions and the language displayed at the language bar. I don't think you can add a language (git is not a language for example) but I might be wrong, do you know how to do it?

**Comment by n6g7** [comment]
I would use a different extension for git (eg. `.sh` or even `.git`) and map it onto another language.
It's true that there is no easy choice for that language, it would have to be abstract.

The colour of the Git logo being red, maybe you could go for HTML? Unless you have plan to have html workouts later on.

**Comment by mathieudutour** [comment]
But it would show HTML in the language bar which would be even more confusing right?

**Comment by n6g7** [comment]
That's right but at the moment the language bar doesn't make sense anyway. I guess you'd have to specify a mapping in the readme.

**Comment by mathieudutour** [comment]
Well it kind of makes sense, the language that you use for git is shell, same as unix ;)

**Comment by arthurbarros** [comment]
Do we have a solution on this ?

**Comment by mathieudutour** [comment]
not really. Any though?

**Comment by michaeljaggers** [comment]
The commit is a really cool idea, if the different topics saved information in their own folders within the language folders, then a script to return the topic values could be used to determine accurate per topic commit info, which could be shared in another way

**Comment by mathieudutour** [comment]
guys I think we broke github, the language bar is not showing anymore. I guess I will close this issue as we can't do anything here anymore.
We might create a page to show global stats later on.
