### ISSUE TITLE
Commits no longer showing

### ISSUE THREAD

**Issue by jacobvarner** [enkidevs/commit#12]
I have starred the repo and my email is the same as my Github account. The commits were showing up perfectly for the first few months of me using the app, but strangely stopped working a few weeks ago. The app still shows my progress, but it stopped showing up as Github commits.

**Comment by mathieudutour** [comment]
Hum weird indeed, it stopped exactly 2 weeks ago, probably when we release the new version. We fixed something related this morning right @spypsy? 

@jacobvarner could you do your workout tomorrow and check if it gets committed? if not, I'll investigate

**Comment by jacobvarner** [comment]
Yes, I'll continue doing my workouts and will report tomorrow if it's fixed or not.

**Comment by tswestendorp** [comment]
Looks like it's fixed

cdc07ed

**Comment by mathieudutour** [comment]
Cool! Let's wait for @jacobvarner's confirmation and I'll close this

**Comment by jacobvarner** [comment]
After the update, it is back to working. Thanks for the fix!
