### ISSUE TITLE
Issues in workouts

### ISSUE THREAD

**Issue by artemgurzhii** [enkidevs/commit#14]
If I have find problem in the daily workout, where should I open issue?

**Comment by mathieudutour** [comment]
What kind of issue is it?

**Comment by artemgurzhii** [comment]
Todays JS workout: Getting the real dimensions of an image

``` javascript
myImg.addEventListener('onload',  function() {
    console.log('Width: ', this.naturalWidth);
    console.log('Height: ', this.naturalHeight);
});
```

should be 

``` javascript
myImg.addEventListener('load',  function() {
    console.log('Width: ', this.naturalWidth);
    console.log('Height: ', this.naturalHeight);
});
```

or

``` javascript
myImg.onload = function() {
    console.log('Width: ', this.naturalWidth);
    console.log('Height: ', this.naturalHeight);
};
```

**Comment by artemgurzhii** [comment]
Also, I have seen some other issues but didn't know where should I open issue. Do you have specific repository for that?

**Comment by mathieudutour** [comment]
No we don't really have a repo for content related issues yet. Feel free to open them here and ping @Loopiezlol

**Comment by mathieudutour** [comment]
If it's a product feature/bug, we are using [product pain](https://productpains.com/product/enki)

**Comment by loopiezlol** [comment]
@artemgurzhii Thanks a bunch for spotting this issue. I have updated the [insight](https://insights.enki.com/insight/567aceb42507c40600683121) accordingly.
