### ISSUE TITLE
Commits not showing up anymore

### ISSUE THREAD

**Issue by mwooddesigns** [enkidevs/commit#18]
I've been using this app for about a week and a half, but after 3 days the commits stopped showing up. They stopped working when I told the app to automatically commit without asking. Disabling the auto commit option doesn't re-enable the manual commits either.

**Comment by lukem512** [comment]
Hi there, are you still experiencing issues with this?

**Comment by mwooddesigns** [comment]
Just checked my commit history and it looks like the commits started working again.
