### ISSUE TITLE
[Question] Linking to existing Github Account?

### ISSUE THREAD

**Issue by The1andONLYdave** [enkidevs/commit#2]
Hey, 

announced in last newsletter was the feature to show up commits in the linked GitHub-Accounts. My Github Account The1andONLYdave is the same as enki, but not case-sensitive. The Mailadress is a different one.

Do i have to change my enki mailadress or is there some web-based backend i don't know off yet?

Thanks in Advance, 
David-Lee

**Comment by mathieudutour** [comment]
You can add your email address that you used on Enki to your [github settings](https://github.com/settings/emails). It will then be linked to your account
