### ISSUE TITLE
Problem in git tools workout

### ISSUE THREAD

**Issue by mohessaid** [enkidevs/commit#22]
I think you have problem in this workout, the credentials cache workout is wrong:
I get the correct one in the 5/5 workout but today [18/10/2016] I get a weird quick workout about the git tools when I started enki for my daily workouts, the workout gave me this question:
`git [------]  [------] credentials.[--------]  [--------]`
Nothing wrong with this question until you check the options:
list of options -> `global`   `--config`  `help`   `cache`

As you can see the `global` and `--config` are mixed up it should be `config` and `--global`, but never mind I though it's a typo problem so I filled the first gap with `--config` and the second with `global`, which gave an error then I scroll down to find the solution that suggest to put `global` first and `--config` in the second gap.

can please check (this is the commit for the weird workout today.

**Comment by mathieudutour** [comment]
@Loopiezlol

**Comment by loopiezlol** [comment]
@mohessaid Thanks for letting us know. I'll take a look and update the workout asap.
