### ISSUE TITLE
Problem in commit timezone

### ISSUE THREAD

**Issue by Fingalzzz** [enkidevs/commit#23]
It seems some timezone problem while commit workout to GitHub.
I start use Enki in 18 Oct, but when I commit in 1am 19 Oct (CST), GitHub showed that I commit twice in 18 Oct.  Now( 2am 20 Oct CST) I open the enki and it said 

> Your workout is done for today, you are on a 2 day streak!

which means I cannot have today's workout.

I'm using Enki in Android 6.0.1, version 0.2.102, hope that would be solved soon.

**Comment by mathieudutour** [comment]
Hi @FingalZhou 

we generate new workouts at 4AM in your timezone. I'm not sure what happen with the commits on the 18th but one was at 4AM and one at 10PM.

I see that you have done your workout 5 hours ago though.

**Comment by Fingalzzz** [comment]
Hi @mathieudutour ,
Did you mean that new workouts would be generated at 4AM each day in my timezone? Why would you do that, it doesn't make any sense in my opinion.

As for commit on 18th, actually I commit once on 18th and the other on the 19th, but both of them shows commit on 18th in GitHub. It seems have some minor bugs there.

**Comment by mathieudutour** [comment]
> Did you mean that new workouts would be generated at 4AM each day in my timezone? Why would you do that, it doesn't make any sense in my opinion.

well we need to do it at one point, we decided 4AM for various reasons, one of them is that people are more likely to be asleep at 4AM than at midnight.

> As for commit on 18th, actually I commit once on 18th and the other on the 19th, but both of them shows commit on 18th in GitHub. It seems have some minor bugs there.

The commit are made from our server which is in GMT so it might not be the same day as yours.
