### ISSUE TITLE
Autocommits to Github doesn't work

### ISSUE THREAD

**Issue by jvlobo** [enkidevs/commit#30]
Yesterday I updated the app with the latest changes to be able to do more than one workout a day.

But now seems like the commits to Github after the workout doesn't work.

Is somebody else experiencing this too?

Cheers!

**Comment by mathieudutour** [comment]
Indeed, there is no commit for anybody for 2 days already.

We are hitting a really weird bug:
    \* the last commit which appear on the github UI and that is returned by the github API is https://github.com/enkidevs/commit/commit/94255102e56b1165dde4f0bc4789de4b603a3a90
    \* but this commit has a child: https://github.com/enkidevs/commit/commit/c393785cadb76ff40b02bec40a1022b3f37eff35
    \* so when we try to commit, we get a 409 saying `refs/head/master is at c393785cadb76ff40b02bec40a1022b3f37eff35 but expected 94255102e56b1165dde4f0bc4789de4b603a3a90`

I'll come back when I have more information

**Comment by mathieudutour** [comment]
Ok I think I fixed it by creating a PR and merging it (I couldn't commit directly to master).

Not sure what happened... We might start to hit the limit of github: 20,000 contributors and 130,000 commits 🙃
