### ISSUE TITLE
Bug opening different courses at the same time.

### ISSUE THREAD

**Issue by Evin1-** [enkidevs/commit#32]
I found a small bug in the Android app where:
I started the **Java** daily course, closed the application, came back and started the **Git** daily course, closed the application, opened and finished the **Java** daily course. Instead of asking me to commit the Java progress, it asked me to do the Git one.

https://github.com/enkidevs/commit/tree/master/contributions/Evin1-

It was my first app launch btw.

**Comment by mathieudutour** [comment]
@Evin1- thanks for the report. There should be a fixed in the version 0.4.3 released yesterday.

Cheers
