### ISSUE TITLE
Workouts complete for today (first time I open the app today)

### ISSUE THREAD

**Issue by jvlobo** [enkidevs/commit#33]
So, I've just opened the app today and it says that I've completed all the workouts...

![img_1062](https://cloud.githubusercontent.com/assets/5671420/20516798/83d742ea-b098-11e6-8675-133700ee59f5.PNG)

It's gonna kill my streak :(

**Comment by TheRealVira** [comment]
I really do not hope that this will be the case, because I do have the same issue and a 80 day streak! I think they are changing some things in the backend, but please do not kill mine for real... 🤐

**Comment by jvlobo** [comment]
It doesn't look good... it has been about 7 hours and I'm still not available to do my today's workout.

I've tried logging out and logging in again, restarting the phone... nothing :(

**Comment by mathieudutour** [comment]
@jvlodo, @TheRealVira, sorry for the delay, the servers were a bit under the weather this night/morning. Your workouts got generated at `2016-11-22T11:14:28.830Z`

 There are no more delays in the workout preparation. Could you check if you receive them? No need to log out/in, just switching tabs should trigger a new fetch.

**Comment by jvlobo** [comment]
Still no workout available @mathieudutour  :/

Edit: worked after logout & login, now I can see workouts!

**Comment by TheRealVira** [comment]
@mathieudutour -> @jvlobos solution worked!

**Comment by mathieudutour** [comment]
Cool, Sorry for the inconvenience.
