### ISSUE TITLE
Commit Feature Gone?

### ISSUE THREAD

**Issue by patrickk** [enkidevs/commit#34]
I recently updated the app to v. 0.4.4 and once I finished a workout for the day, I wasn't asked to commit my progress. Is the feature gone as of this update? Thank you.

**Comment by bbohac** [comment]
The release notes for the Android version clearly state:

> The app will no longer commit workout progress to GitHub. The repo became so large that GitHub shut us down. Whoops!

So, yes, the feature is gone.

**Comment by patrickk** [comment]
Silly me, should've read em. Thanks!

**Comment by mathieudutour** [comment]
Yes sorry about that, we are writing a small piece to explain a bit more what happen. Should be interesting to read, stay tuned :)

**Comment by andrewda** [comment]
Just curious - would it be possible to create a new repository every month or two?

**Comment by mathieudutour** [comment]
Github has been quite clear that it would not work, no. The only solution would be to create 1 repo per person on their account. So we would need a lot more permissions from you and the leaderboard wouldn't work. So that's not something that we are gonna do for now.

**Comment by Rainsho** [comment]
@mathieudutour would it be possible to merge each user's workout into a signal file, just like a workout log for each user?

**Comment by mathieudutour** [comment]
That's possible but it's not a solution: the issue is not size of the files in the repo, it's the size of the git tree which grows with every commits and every contributors. Even having just empty commits wouldn't fix the issue.

**Comment by AjkP** [comment]
Just my $0.02, but I liked the commit feature. It would at least give you some log for your efforts.
